
services:
  mysql:
    image: mysql:8.0  # 使用8.0版本的 MySQL 镜像
    container_name: my-mysql  # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 MySQL root 用户的密码
    ports:
      - "3307:3306"  # 将容器的 3306 端口映射到宿主机的 3307 端口
    volumes:
      - ./data/mysql:/var/lib/mysql  # 将宿主机的 /data/mysql 目录挂载到容器的 /var/lib/mysql 目录
    restart: always  # 容器退出后总是重启

  redis:
    image: redis:7-alpine  # 使用7.x版本的 Redis 镜像
    container_name: my-redis  # 容器名称
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]
    ports:
      - "6379:6379"  # 将容器的 6379 端口映射到宿主机的 6379 端口
    volumes:
      - ./data/redis:/data  # 将宿主机的 /data/redis 目录挂载到容器的数据目录
    restart: always  # 容器退出后总是重启

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: my-etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_DATA_DIR=/var/lib/etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379 # 对外暴露的地址
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 监听地址
    volumes:
      - ./data/etcd:/var/lib/etcd
    
  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    platform: linux/amd64
    container_name: etcd-ui
    ports:
      - "8000:8080"
    environment:
      - ETCD_SERVERS=http://etcd:2379 # 使用etcd的服务器进行连接
    depends_on:
      - etcd

  mall_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mall-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - ETCD_ADDR=http://127.0.0.1:2379
    working_dir: /data/wwwRoot
    command: ["./mall.backend"]
    network_mode: "host"