version: '3.8'

services:
  mysql:
    image: mysql:8.0  # 使用8.0版本的 MySQL 镜像
    container_name: my-mysql  # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # 设置 MySQL root 用户的密码
    ports:
      - "3307:3306"  # 将容器的 3306 端口映射到宿主机的 3307 端口
    volumes:
      - ~/data/mysql:/var/lib/mysql  # 将宿主机的 /data/mysql 目录挂载到容器的 /var/lib/mysql 目录
    restart: always  # 容器退出后总是重启

  redis:
    image: redis:7-alpine  # 使用7.x版本的 Redis 镜像
    container_name: my-redis  # 容器名称
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "123456"]
    ports:
      - "6379:6379"  # 将容器的 6379 端口映射到宿主机的 6379 端口
    volumes:
      - ~/data/redis:/data  # 将宿主机的 /data/redis 目录挂载到容器的数据目录
    restart: always  # 容器退出后总是重启
