// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminUser = "admin_user"

// AdminUser mapped from table <admin_user>
type AdminUser struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:-ID" json:"id"` // -ID
	Name       string    `gorm:"column:name;not null" json:"name"`
	NickName   string    `gorm:"column:nick_name;not null" json:"nick_name"`
	Mobile     string    `gorm:"column:mobile;not null" json:"mobile"`
	LarkOpenID string    `gorm:"column:lark_open_id;not null;comment:openid" json:"lark_open_id"` // openid
	Password   string    `gorm:"column:password;not null" json:"password"`
	Status     int32     `gorm:"column:status;not null;default:1;comment:1: -1" json:"status"` // 1: -1
	CreateAt   time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt   time.Time `gorm:"column:update_at;not null" json:"update_at"`
	CreateBy   int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy   int64     `gorm:"column:update_by;not null;default:1" json:"update_by"`
	Sex        int32     `gorm:"column:sex;not null;default:3;comment:3: 1 2" json:"sex"` // 3: 1 2
	IsDelete   int32     `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
