// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAppUser = "app_user"

// AppUser mapped from table <app_user>
type AppUser struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID   int64     `gorm:"column:user_id;not null;comment:id,user" json:"user_id"`      // id,user
	AppCode  int32     `gorm:"column:app_code;not null;comment:1000=1001=" json:"app_code"` // 1000=1001=
	OpenID   string    `gorm:"column:open_id;not null;comment:openid" json:"open_id"`       // openid
	Status   int32     `gorm:"column:status;not null;default:1;comment:1 -1" json:"status"` // 1 -1
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName AppUser's table name
func (*AppUser) TableName() string {
	return TableNameAppUser
}
