// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseLesson = "course_lessons"

// CourseLesson mapped from table <course_lessons>
type CourseLesson struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CourseGoodsID int64     `gorm:"column:course_goods_id;not null" json:"course_goods_id"`
	CatalogID     int64     `gorm:"column:catalog_id;not null" json:"catalog_id"`
	Name          string    `gorm:"column:name;not null;comment:-" json:"name"`                  // -
	LessonID      int64     `gorm:"column:lesson_id;not null;comment:ID" json:"lesson_id"`       // ID
	EnableTrial   int32     `gorm:"column:enable_trial;not null;comment:1:" json:"enable_trial"` // 1:
	Sort          int32     `gorm:"column:sort;not null" json:"sort"`
	ShowTime      time.Time `gorm:"column:show_time;not null" json:"show_time"`
	UpdateAt      time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy      int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName CourseLesson's table name
func (*CourseLesson) TableName() string {
	return TableNameCourseLesson
}
