// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourseGood = "course_goods"

// CourseGood mapped from table <course_goods>
type CourseGood struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	CoverKey       string `gorm:"column:cover_key;not null;comment:key" json:"cover_key"`               // key
	DetailCoverKey string `gorm:"column:detail_cover_key;not null;comment:key" json:"detail_cover_key"` // key
	Detail         string `gorm:"column:detail;not null" json:"detail"`
	CoursePrice    int64  `gorm:"column:course_price;not null" json:"course_price"`
	/*

		1 2 3 4
	*/
	ServiceTime  int32     `gorm:"column:service_time;not null;comment:\n1 2 3 4" json:"service_time"`
	LearnTime    int32     `gorm:"column:learn_time;not null;comment:1 2 3 4" json:"learn_time"` // 1 2 3 4
	Status       int32     `gorm:"column:status;not null;default:-1;comment:-1 1" json:"status"` // -1 1
	Sort         int32     `gorm:"column:sort;not null" json:"sort"`
	Features     string    `gorm:"column:features;not null" json:"features"`
	UpdateStatus int32     `gorm:"column:update_status;not null;comment:1:  2" json:"update_status"` // 1:  2
	CreateAt     time.Time `gorm:"column:create_at;not null" json:"create_at"`
	CreateBy     int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy     int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName CourseGood's table name
func (*CourseGood) TableName() string {
	return TableNameCourseGood
}
