// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLesson = "lessons"

// Lesson mapped from table <lessons>
type Lesson struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string `gorm:"column:name;not null" json:"name"`
	Detail        string `gorm:"column:detail;not null" json:"detail"`
	CategoryID    int64  `gorm:"column:category_id;not null;comment:ID" json:"category_id"` // ID
	VideoKey      string `gorm:"column:video_key;not null;comment:key" json:"video_key"`    // key
	VideoFileName string `gorm:"column:video_file_name;not null" json:"video_file_name"`
	Duration      int32  `gorm:"column:duration;not null" json:"duration"`
	Attachments   string `gorm:"column:attachments;not null;comment:[{"file_key": "", "file_name": "", "file_type": ""}]" json:"attachments"` // [{"file_key": "", "file_name": "", "file_type": ""}]
	/*
		[{
		  "id": "dddd",
		   "name": "dddd",
		   "begin_position": 1,
		   "end_position": 1
		}]
	*/
	Chapters string    `gorm:"column:chapters;not null;comment:[{\n  "id": "dddd",\n   "name": "dddd",\n   "begin_position": 1,\n   "end_position": 1\n}]" json:"chapters"`
	Status   int32     `gorm:"column:status;not null;comment:1  -1" json:"status"` // 1  -1
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Lesson's table name
func (*Lesson) TableName() string {
	return TableNameLesson
}
