// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonLearnRecord = "lesson_learn_record"

// LessonLearnRecord mapped from table <lesson_learn_record>
type LessonLearnRecord struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CourseID         int64     `gorm:"column:course_id;not null;comment:ID" json:"course_id"`                   // ID
	LessonID         int64     `gorm:"column:lesson_id;not null;comment:ID" json:"lesson_id"`                   // ID
	FirstCategoryID  int64     `gorm:"column:first_category_id;not null;comment:id" json:"first_category_id"`   // id
	SecondCategoryID int64     `gorm:"column:second_category_id;not null;comment:id" json:"second_category_id"` // id
	EntryTime        time.Time `gorm:"column:entry_time;not null" json:"entry_time"`
	ExitTime         time.Time `gorm:"column:exit_time;not null" json:"exit_time"`
	Duration         int64     `gorm:"column:duration;not null" json:"duration"`
	LastType         int32     `gorm:"column:last_type;not null" json:"last_type"`
	UserID           int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName LessonLearnRecord's table name
func (*LessonLearnRecord) TableName() string {
	return TableNameLessonLearnRecord
}
