// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMobileUser = "mobile_user"

// MobileUser mapped from table <mobile_user>
type MobileUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64     `gorm:"column:user_id;not null;comment:user" json:"user_id"`                // user
	MobileAes    string    `gorm:"column:mobile_aes;not null;comment:aes," json:"mobile_aes"`          // aes,
	MobileSha256 string    `gorm:"column:mobile_sha256;not null;comment:sha256," json:"mobile_sha256"` // sha256,
	CreateAt     time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt     time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName MobileUser's table name
func (*MobileUser) TableName() string {
	return TableNameMobileUser
}
