// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderItem = "order_items"

// OrderItem mapped from table <order_items>
type OrderItem struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OrderID        int64  `gorm:"column:order_id;not null" json:"order_id"`
	UserID         int64  `gorm:"column:user_id;not null" json:"user_id"`
	GoodsID        int64  `gorm:"column:goods_id;not null;comment:ID" json:"goods_id"`               // ID
	GoodsType      int32  `gorm:"column:goods_type;not null;default:1;comment:1:" json:"goods_type"` // 1:
	Quantity       int32  `gorm:"column:quantity;not null;default:1" json:"quantity"`
	PaymentAmount  int64  `gorm:"column:payment_amount;not null" json:"payment_amount"`
	DiscountAmount int64  `gorm:"column:discount_amount;not null" json:"discount_amount"`
	GoodsSnap      string `gorm:"column:goods_snap;not null" json:"goods_snap"`
}

// TableName OrderItem's table name
func (*OrderItem) TableName() string {
	return TableNameOrderItem
}
