// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrderRefund = "order_refunds"

// OrderRefund mapped from table <order_refunds>
type OrderRefund struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID       int64  `gorm:"column:user_id;not null" json:"user_id"`
	OrderID      int64  `gorm:"column:order_id;not null" json:"order_id"`
	ItemIds      string `gorm:"column:item_ids;not null" json:"item_ids"`
	ApplyAt      int64  `gorm:"column:apply_at;not null" json:"apply_at"`
	Reason       string `gorm:"column:reason;not null" json:"reason"`
	Status       int32  `gorm:"column:status;not null;comment:// 0123" json:"status"` // // 0123
	Amount       int64  `gorm:"column:amount;not null" json:"amount"`
	InnerTradeNo string `gorm:"column:inner_trade_no;not null" json:"inner_trade_no"`
	RefundID     string `gorm:"column:refund_id;not null" json:"refund_id"`
	ApplyUserID  int64  `gorm:"column:apply_user_id;not null" json:"apply_user_id"`
	DoneAt       int64  `gorm:"column:done_at;not null" json:"done_at"`
}

// TableName OrderRefund's table name
func (*OrderRefund) TableName() string {
	return TableNameOrderRefund
}
