// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID                  int64   `gorm:"column:id;primaryKey" json:"id"`
	UserID              int64   `gorm:"column:user_id;not null;comment:ID" json:"user_id"`                       // ID
	Status              int32   `gorm:"column:status;not null;default:1;comment:-11:  2 3  4 5 6" json:"status"` // -11:  2 3  4 5 6
	OrderSource         int32   `gorm:"column:order_source;not null;comment:1  2  3" json:"order_source"`        // 1  2  3
	OrderAmount         int64   `gorm:"column:order_amount;not null;comment:=" json:"order_amount"`              // =
	DiscountAmount      int64   `gorm:"column:discount_amount;not null" json:"discount_amount"`
	PaymentAmount       int64   `gorm:"column:payment_amount;not null;comment:-" json:"payment_amount"` // -
	TradeNo             string  `gorm:"column:trade_no;not null" json:"trade_no"`
	InnerTradeNo        string  `gorm:"column:inner_trade_no;not null" json:"inner_trade_no"`
	OrderDesc           string  `gorm:"column:order_desc;not null" json:"order_desc"`
	PaymentAt           int64   `gorm:"column:payment_at;not null;comment:," json:"payment_at"` // ,
	UserRemark          string  `gorm:"column:user_remark;not null" json:"user_remark"`
	ReceiverConfirmAt   *int64  `gorm:"column:receiver_confirm_at" json:"receiver_confirm_at"`
	ReceiverConfirmType *int32  `gorm:"column:receiver_confirm_type;comment: 1  99:10" json:"receiver_confirm_type"` //  1  99:10
	RefundAmount        int64   `gorm:"column:refund_amount;not null" json:"refund_amount"`
	RefundAt            *int64  `gorm:"column:refund_at" json:"refund_at"`
	CancelAt            *int64  `gorm:"column:cancel_at" json:"cancel_at"`
	CancelType          *int32  `gorm:"column:cancel_type;comment:1:   2  3:" json:"cancel_type"` // 1:   2  3:
	CancelBy            *int64  `gorm:"column:cancel_by;comment:ID  -1" json:"cancel_by"`         // ID  -1
	CancelReason        *string `gorm:"column:cancel_reason" json:"cancel_reason"`
	CreateAt            int64   `gorm:"column:create_at;not null" json:"create_at"`
	CreateBy            int64   `gorm:"column:create_by;not null;comment:IDorder_sourceID-1" json:"create_by"` // IDorder_sourceID-1
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
