// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permission"

// Permission mapped from table <permission>
type Permission struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code     string    `gorm:"column:code;not null" json:"code"`
	Type     int32     `gorm:"column:type;not null;comment:1:  2" json:"type"` // 1:  2
	Name     string    `gorm:"column:name;not null" json:"name"`
	PagePath string    `gorm:"column:page_path;not null" json:"page_path"`
	ParentID int64     `gorm:"column:parent_id;not null;default:-1;comment:ID" json:"parent_id"` // ID
	Status   int32     `gorm:"column:status;not null;comment:1 -1" json:"status"`                // 1 -1
	Sort     int32     `gorm:"column:sort;not null;default:1" json:"sort"`
	Desc     string    `gorm:"column:desc;not null" json:"desc"`
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
