// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceUploadFile = "resource_upload_files"

// ResourceUploadFile mapped from table <resource_upload_files>
type ResourceUploadFile struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Scene          string    `gorm:"column:scene;not null" json:"scene"`
	FileKey        string    `gorm:"column:file_key;not null;comment:key," json:"file_key"` // key,
	UserID         int64     `gorm:"column:user_id;not null;comment:id" json:"user_id"`     // id
	UserType       int32     `gorm:"column:user_type;not null" json:"user_type"`
	FileType       string    `gorm:"column:file_type;not null;comment:" json:"file_type"` //
	FileSize       int64     `gorm:"column:file_size;not null" json:"file_size"`
	FileName       string    `gorm:"column:file_name;not null" json:"file_name"`
	UploadClientIP string    `gorm:"column:upload_client_ip;not null;comment:ip" json:"upload_client_ip"`            // ip
	CreateAt       time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:=" json:"create_at"` // =
}

// TableName ResourceUploadFile's table name
func (*ResourceUploadFile) TableName() string {
	return TableNameResourceUploadFile
}
