// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string    `gorm:"column:name;not null" json:"name"`
	Desc     string    `gorm:"column:desc;not null" json:"desc"`
	Status   int32     `gorm:"column:status;not null;comment:1: -1" json:"status"` // 1: -1
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreateBy int64     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy int64     `gorm:"column:update_by;not null" json:"update_by"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
