// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmsTemplate = "sms_template"

// SmsTemplate mapped from table <sms_template>
type SmsTemplate struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SceneCode      string    `gorm:"column:scene_code;not null" json:"scene_code"`
	SignName       string    `gorm:"column:sign_name;not null" json:"sign_name"`
	PlatformTmplID int32     `gorm:"column:platform_tmpl_id;not null;comment:ID" json:"platform_tmpl_id"` // ID
	TmplStr        string    `gorm:"column:tmpl_str;not null" json:"tmpl_str"`
	Status         int32     `gorm:"column:status;not null;default:1;comment:1 -1" json:"status"` // 1 -1
	CreateAt       time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt       time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	AdminUserID    int64     `gorm:"column:admin_user_id;not null;comment:admin_user_id" json:"admin_user_id"` // admin_user_id
	Platform       string    `gorm:"column:platform;not null;comment:tencent, ronglian" json:"platform"`       // tencent, ronglian
}

// TableName SmsTemplate's table name
func (*SmsTemplate) TableName() string {
	return TableNameSmsTemplate
}
