// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:user_id" json:"id"` // user_id
	NickName    string    `gorm:"column:nick_name;not null" json:"nick_name"`
	Sex         int32     `gorm:"column:sex;not null;comment:0  1 2" json:"sex"`                 // 0  1 2
	Password    string    `gorm:"column:password;not null;comment:64" json:"password"`           // 64
	Status      int32     `gorm:"column:status;not null;default:1;comment:1  -1" json:"status"`  // 1  -1
	IconKey     string    `gorm:"column:icon_key;not null;comment:32key uuid -" json:"icon_key"` // 32key uuid -
	CreateAt    time.Time `gorm:"column:create_at;not null" json:"create_at"`
	LastLoginAt time.Time `gorm:"column:last_login_at;not null" json:"last_login_at"`
	UpdateAt    time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
