// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCourseGood = "user_course_goods"

// UserCourseGood mapped from table <user_course_goods>
type UserCourseGood struct {
	ID                int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID            int64 `gorm:"column:user_id;not null;comment:ID" json:"user_id"`             // ID
	OrderID           int64 `gorm:"column:order_id;not null;comment:ID" json:"order_id"`           // ID
	OrderItemID       int64 `gorm:"column:order_item_id;not null;comment:ID" json:"order_item_id"` // ID
	GoodsID           int64 `gorm:"column:goods_id;not null;comment:ID" json:"goods_id"`           // ID
	GoodsType         int32 `gorm:"column:goods_type;not null;comment:1." json:"goods_type"`       // 1.
	BuyTime           int64 `gorm:"column:buy_time;not null" json:"buy_time"`
	LearnExpireTime   int64 `gorm:"column:learn_expire_time;not null" json:"learn_expire_time"`
	ServiceExpireTime int64 `gorm:"column:service_expire_time;not null" json:"service_expire_time"`
}

// TableName UserCourseGood's table name
func (*UserCourseGood) TableName() string {
	return TableNameUserCourseGood
}
