// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWechatUser = "wechat_user"

// WechatUser mapped from table <wechat_user>
type WechatUser struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID," json:"id"` // ID,
	UserID   int64     `gorm:"column:user_id;not null;comment:id,user" json:"user_id"`        // id,user
	UnionID  string    `gorm:"column:union_id;not null;comment:ID" json:"union_id"`           // ID
	NickName string    `gorm:"column:nick_name;not null" json:"nick_name"`
	IconURL  string    `gorm:"column:icon_url;not null;comment:128" json:"icon_url"` // 128
	CreateAt time.Time `gorm:"column:create_at;not null" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null" json:"update_at"`
}

// TableName WechatUser's table name
func (*WechatUser) TableName() string {
	return TableNameWechatUser
}
